### ISSUE TITLE
ENABLE_GPU_ACCELERATION is processing slow 

### ISSUE THREAD

**Issue by andikaMaulana** [nicholaskajoh/ivy#38]
when i ENABLE_GPU_ACCELERATION=True, processing my video is running slow. My GPU is Nvidia RTX 2080 TI.

**Comment by nicholaskajoh** [comment]
Hi @andikaMaulana! Can you please quantify? How slow? You can check the logs for the processing frame rate (label: `FRAME_PROCESS`). Also, what detection model are you using?

By the way, did you follow the instructions in #34?

_PS: Ivy doesn't run in realtime yet. But we're working on getting there._

**Comment by andikaMaulana** [comment]
> Hi @andikaMaulana! Can you please quantify? How slow? You can check the logs for the processing frame rate (label: `FRAME_PROCESS`). Also, what detection model are you using?
> 
> By the way, did you follow the instructions in #34?
> 
> _PS: Ivy doesn't run in realtime yet. But we're working on getting there._

I using yolo detection model.

**Comment by byq-luo** [comment]
Create .env from .env.example in the project root and edit as appropriate.
What should I do in this step? Thank you for your guidance

**Comment by nicholaskajoh** [comment]
Use .env.example as an example to create a .env file. On a unix shell, you can run `cp .env.example .env` and then edit .env in your text editor to suit your needs.

How do you think this instruction can be better worded to make it easier to understood?

**Comment by byq-luo** [comment]
Thank you!

**Comment by byq-luo** [comment]
> Use .env.example as an example to create a .env file. On a unix shell, you can run `cp .env.example .env` and then edit .env in your text editor to suit your needs.
> 
> How do you think this instruction can be better worded to make it easier to understand?

Thank you!

**Comment by byq-luo** [comment]
> Use .env.example as an example to create a .env file. On a unix shell, you can run `cp .env.example .env` and then edit .env in your text editor to suit your needs.
> How do you think this instruction can be better worded to make it easier to understand?

I have solved, thank the great.

**Comment by andikaMaulana** [comment]
solved, I uninstall yolo34py lib, then i install yolo34py-gpu.
