### ISSUE TITLE
Tracker module installation

### ISSUE THREAD

**Issue by himakarbavikaty** [nicholaskajoh/ivy#47]
Hi, 

I have gone through document. It is really interesting. I am unable tracker module. I am getting the following error.ImportError: cannot import name 'izip_longest'. Can you help me to proceed further

**Comment by nicholaskajoh** [comment]
Hi @himakarbavikaty, can you share the full stack trace of the error you're getting?

**Comment by himakarbavikaty** [comment]
I am very thankful for your response Nicholas. I installed tracker module with pip. I am getting the following error while importing package.

import tracker

when i am executing the above import statement, I am getting the following error.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-bbfaf92f8ca0> in <module>
----> 1 import tracker

E:\ProgramData\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tracker\__init__.py in <module>
----> 1 from .tracker import tracked

E:\ProgramData\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tracker\tracker.py in <module>
      2 import inspect
      3 
----> 4 from .snapshot import Snapshot
      5 
      6 

E:\ProgramData\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tracker\snapshot.py in <module>
      1 import textwrap
----> 2 from itertools import izip_longest
      3 
      4 from .tracker import __file__ as SOURCE_FILE
      5 

ImportError: cannot import name 'izip_longest'

**Comment by nicholaskajoh** [comment]
Hmm... 🤔 Can you explain what you're trying to achieve? Not sure I'm following. Why do you want to import tracker?

**Comment by himakarbavikaty** [comment]
I want to count number of vehicles which pass through our camera. Later I want to detect speed of the vehicle.

**Comment by nicholaskajoh** [comment]
You don't need to modify the code to count vehicles. It already does that. Except there's some specify capability you want that isn't implemented.

For speed detection, we don't yet support it but it's something we're interested in. If you have ideas on how it could be done accurately and efficiently, we can figure it out together.
