### ISSUE TITLE
Yolo+KCF is faster than Yolo + SORT

### ISSUE THREAD

**Issue by Water2style** [nicholaskajoh/ivy#48]
This ivy project is very good!

everyone says that SORT is faster than KCF.
But in my another project that i used Yolo + SORT,  i found that the KCF in this repo is faster than SORT
Why is that?

**Comment by nicholaskajoh** [comment]
I haven't used SORT before so I don't have an idea of how it performs relative to KCF. I'll give it a try and see how it goes!
