### ISSUE TITLE
I got Error when i try to run code.

### ISSUE THREAD

**Issue by rashiddaha** [nicholaskajoh/ivy#49]
Path to video file not set.
YOLO_WEIGHTS_PATH, YOLO_CONFIG_PATH, YOLO_CLASSES_PATH, YOLO_CLASSES_OF_INTEREST_PATH, and/or YOLO_CONFIDENCE_THRESHOLD not set or invalid.
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    import settings
  File "D:\Project1\ivy-master\settings.py", line 214, in <module>
    raise Exception('One or more environment variables are either invalid or not set. ' +
Exception: One or more environment variables are either invalid or not set. Please ensure all variables are properly set.

**Comment by nicholaskajoh** [comment]
Have you create a .env file? Please see https://github.com/nicholaskajoh/ivy/blob/master/.env.example.

**Comment by rashiddaha** [comment]
No, can you help me in creating and setup this code to work ?my email is rashiddaha80@gmail.com

**Comment by rashiddaha** [comment]
if you come to teamviewer ,i will be thankful .

**Comment by rashiddaha** [comment]
i will pay 20$. if you help me out

**Comment by nicholaskajoh** [comment]
Sorry for the late response.
Check if the environment variables are available in the terminal session you're running the program in. If not, you can manually set them.

**Comment by ha-daiy** [comment]
This could help:
[https://github.com/nicholaskajoh/ivy/issues/52#issuecomment-1272508325](url)
