### ISSUE TITLE
recipe for target 'obj/convolutional_kernels.o' failed

### ISSUE THREAD

**Issue by Geobm** [nicholaskajoh/ivy#50]
Hi @nicholaskajoh, 

I would like to use the demo of your repo but I'm gettin the following error when running ```make``` once I cloned the [darknet repo](https://github.com/pjreddie/darknet) and installed its dependencies in order to use YOLO. Also, I am using Ubuntu 18.04.1.

``` 
$ sudo make
```

```
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ --compiler-options "-Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
nvcc fatal   : Path to libdevice library not specified
Makefile:92: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1

```
I supposed it could be something wrong  with CUDA's path as suggested by this [comment](https://github.com/pjreddie/darknet/issues/200#issuecomment-329692411). Since the path in the Makefile its the same in **/usr/local/cuda/include/**
```
ifeq ($(GPU), 1) 
COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand
endif
```
Tried the following command ``` export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}``` as mentioned but could not fix it.

Any suggestion of what I'm doing wrong will be appreciated

**Comment by nicholaskajoh** [comment]
You don't need to install darknet. OpenCV has a [DNN module that can handle darknet models](https://github.com/nicholaskajoh/ivy/blob/9974369d6fff7f6556a61654dde226158c02509a/detectors/yolo.py#L18). Once you install the dependencies in requirements.txt, you're good.
