### ISSUE TITLE
Adding a custom detector

### ISSUE THREAD

**Issue by spranjal25** [nicholaskajoh/ivy#51]
How can we add a custom detector to this module? I have a faster RCNN based detector which I added as a python file having the exact get_bounding_boxes() function which returns the bounding boxes, scores and the classes. I added it in the detectors directory but when I run the main.py file it gives:
"ERROR   : Invalid detector model, algorithm or API specified (options: yolo, tfoda, detectron2, haarcascade) {'label': 'INVALID_DETECTION_ALGORITHM'}"
I checked in the .env file but I cannot seem to find what path may be added for the detector to run my fasterrcnn.py file instead of the given yolo.py, tfoda.py etc.
Could you help me out with this one?

**Comment by nicholaskajoh** [comment]
Here: https://github.com/nicholaskajoh/ivy/blob/master/detectors/detector.py

**Comment by spranjal25** [comment]
Thanks a ton! still wondering how I missed that :o.
