### ISSUE TITLE
raise Exception('One or more environment variables are either invalid or not set. ' + Exception: One or more environment variables are either invalid or not set. Please ensure all variables are properly set.

### ISSUE THREAD

**Issue by NewPenguin** [nicholaskajoh/ivy#52]
Hi, Pardon my weakness in understanding. 
i was attempting to run `python -m main` as stated in the page. But i gotten this error, may i know more about it and how to solve it?
![image](https://user-images.githubusercontent.com/50839211/91249123-d4347e80-e788-11ea-926b-ab2b36a2183f.png)

**Comment by nicholaskajoh** [comment]
Hey @NewPenguin! You need to load the required environment variables. Please see [.env.example](https://github.com/nicholaskajoh/ivy/blob/master/.env.example).

**Comment by ha-daiy** [comment]
In the root directory, I rename the file `.env.example` to `.env` by using the following command:
`mv .env.example .env`.
The error disappeared.
