### ISSUE TITLE
ERROR in debug mode

### ISSUE THREAD

**Issue by abhaysingh1998** [nicholaskajoh/ivy#54]
Hello! In debug mode after running for sometime your software halts and exits with the following error on the terminal.

**OpenCL error CL_INVALID_COMMAND_QUEUE (-36) during call: clEnqueueNDRangeKernel('tmm', dims=2, globalsize=640x10x1, localsize=64x1x1) sync=true
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.1.0) Error: Unknown error code -220 (OpenCL error CL_INVALID_COMMAND_QUEUE (-36) during call: clEnqueueMapBuffer(handle=2F5917C8, sz=1443360) => 00000000) in cv::ocl::OpenCLAllocator::deallocate_, file C:\projects\opencv-python\opencv\modules\core\src\ocl.cpp, line 4881**

Please have a look at it. Thanks !!

**Comment by nicholaskajoh** [comment]
Can you provide more information so I can reproduce it?

**Comment by abhaysingh1998** [comment]
Ok, so I'm on **windows** right now and using **python3.7**
1) I **cloned** the project 
2) Installed all the dependencies listed in **requirements.txt** using pip
3) Downloaded the **demo data** (sample video, etc)
4) Did **python -m main** in the project directory 
5) It runs successfully but after some time, maybe after detecting and counting 2-3 objects in the video it halts and exits with the above error message on the terminal.

I can attach the screencast of this if you want ....
Thanks !!

**Comment by nicholaskajoh** [comment]
Yes, a screencast would be helpful.

**Comment by nicholaskajoh** [comment]
Does the issue you're experiencing only occur in debug mode?
