### ISSUE TITLE
Error trying to run the detector

### ISSUE THREAD

**Issue by Davo-Exp4** [nicholaskajoh/ivy#61]
SIr thank you for sharing this awesome project. I have a problem trying to running this project, I successfully passed the python -m pytest command even the python -m main command but  when  it "detects" something in this case a car I have this issue:

File "/home/davo/Downloads/TProjects/ivy/main.py", line 111, in run
    object_counter.count(frame)
  File "/home/davo/Downloads/TProjects/ivy/ObjectCounter.py", line 74, in count
    self.blobs = add_new_blobs(_bounding_boxes, _classes, _confidences, self.blobs, self.frame, self.tracker, self.mcdf)
  File "/home/davo/Downloads/TProjects/ivy/tracker.py", line 66, in add_new_blobs
    _tracker = get_tracker(tracker, box, frame)
  File "/home/davo/Downloads/TProjects/ivy/tracker.py", line 40, in get_tracker
    return _kcf_create(bounding_box, frame)
  File "/home/davo/Downloads/TProjects/ivy/tracker.py", line 30, in _kcf_create
    tracker.init(frame, tuple(bounding_box))
TypeError: integer argument expected, got float

I am trying to debug this problem but I think I am stuck. I am using yolo as my detection algorithm. Thank you sir.

**Comment by Davo-Exp4** [comment]
Sir, I think i figured out, I parsed the  x and y coordinates to int  of the bounding box in yolo.py script 

x = int(center_x - w / 2)
y = int(center_y - h / 2)

and now it runs correctly. 
Thank you Sir.

**Comment by nicholaskajoh** [comment]
Hey @Davo-Exp4, please can you send a patch? :)

**Comment by Davo-Exp4** [comment]
No problem @nicholaskajoh  patch is on its way! :)

**Comment by nicholaskajoh** [comment]
Merci beaucoup!
